### ISSUE TITLE
I would very much like some comments...

### ISSUE THREAD

**Issue by thisguycodes** [Cristofori/kmud#2]
on https://github.com/Cristofori/kmud/blob/master/telnet/telnet.go , I thought I knew what the listenfunc did but apparently I don't, or I do but I'm misunderstanding something else about my current adhoc testing. And I don't quite understand what `(*Telnet) Data` is supposed to do, since I doubt `t.Data(telnet.WILL)` or `t.Data(telnet.AYT)` makes much sense.

I can make a bunch of assumptions I think are right, but it'd be awesome if the generated documentation wasn't just a list of function signatures :)

**Comment by Cristofori** [comment]
listenfunc was something I threw in so that I could have a routine that monitored the values of certain commands (like window size and terminal type). You can see an example of its usage in `server.go`.

The `Data` method is there so that you can retrieve the values of commands (like window size) on demand. Obviously it doesn't make sense for every single kind of telnet code.

**Comment by thisguycodes** [comment]
is it appropriate to use listenfunc to receive live updates on things like GMCP, or other sub-option commands?

**Comment by Cristofori** [comment]
I think it should work fine for that

**Comment by thisguycodes** [comment]
It doesn't seem to be... but rather than ad-hoc debugging (which I'm still happy to do!) I created a failing test in #3 that illustrates my expectations (and uses a real world example).

**Comment by Cristofori** [comment]
So `listenFunc` is only going to be called back after a sub negotiation has been completed (like what happens when the client's window size is specificed), the example you've given in your test has no sub negotation parameters.

**Comment by thisguycodes** [comment]
oh... ok that's not really what I was looking for. Knowing that I can more easily make sense of the byte processing code now, I'll probably fork and make what I want (and pr later in case you want it!) :)

Thanks for the clarification!
