### ISSUE TITLE
Getting out of commands

### ISSUE THREAD

**Issue by necrogami** [Cristofori/kmud#4]
There needs to be a way to get out of commands or up a tier in commands i can't seem to find a way with code.

**Comment by Cristofori** [comment]
Hit x

**Comment by necrogami** [comment]
You might want to add that to the commands as trying to find that is extremely frustrating and i couldn't find it in the code.

**Comment by Cristofori** [comment]
Yep. Usability issues are generally pretty low on the priority list at the moment.
